version: '3'

services:
  react:
    build:
      args:
        - VERSION=latest
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./projects:/usr/src/app
    environment:
      - WATCHPACK_POLLING=true
    tty: true